# Generated by Django 4.2.7 on 2023-12-05 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_task_created_task_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('now', models.DateField(auto_now=True, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['completed', '-updated']},
        ),
    ]
