# Generated by Django 4.2.7 on 2023-12-05 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_date_alter_task_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='now',
            field=models.DateField(),
        ),
    ]
