# Generated by Django 4.2.7 on 2023-12-05 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_date_now'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='date',
            options={'ordering': ['-now']},
        ),
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.date'),
        ),
    ]
