# Generated by Django 4.2.7 on 2023-12-26 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_task_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Date',
        ),
    ]
